// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.StudyField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Business Management"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Softwarový vývoj"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.StudyYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Year = 1
                        },
                        new
                        {
                            Id = 2,
                            Year = 2
                        },
                        new
                        {
                            Id = 3,
                            Year = 3
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anglický jazyk",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inovace v podnikání",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lidské zdroje",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Management",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marketing",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mezinárodní obchod",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Podniková etika",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Projektový management",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Strategické řízení",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Účetnictví",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Veřejné finance",
                            StudyFieldId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Algoritmy",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Anglický jazyk",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bezpečnost softwaru",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cloud Computing",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Databáze",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Data Science",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Matematika",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "Obchodní právo",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Operační systémy",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Programování",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Software Engineering",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "Systémová architektura",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 25,
                            Name = "UI/UX Design",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "Umělá inteligence",
                            StudyFieldId = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "Web Development",
                            StudyFieldId = 2
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Subject", b =>
                {
                    b.HasOne("Infrastructure.Entities.StudyField", "StudyField")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("Infrastructure.Entities.StudyField", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
